#Source path
train_feat_path: 'timit_for_GAN/audio/timit-train-mfcc-nor.pkl'
train_orc_bnd_path: 'timit_for_GAN/audio/timit-train-orc1-bnd.pkl'
train_phn_path: 'timit_for_GAN/audio/timit-train-phn.pkl'

dev_feat_path: 'timit_for_GAN/audio/timit-dev-mfcc-nor.pkl'
dev_orc_bnd_path: 'timit_for_GAN/audio/timit-dev-orc1-bnd.pkl'
dev_phn_path: 'timit_for_GAN/audio/timit-dev-phn.pkl'

test_feat_path: 'timit_for_GAN/audio/timit-test-mfcc-nor.pkl'
test_orc_bnd_path: 'timit_for_GAN/audio/timit-test-orc1-bnd.pkl'
test_phn_path: 'timit_for_GAN/audio/timit-test-phn.pkl'

# Model
# generator
gen_hidden_size: 512
# others
seg_loss_ratio: 0.5
penalty_ratio: 10
frame_temp: 0.9

# discriminator
target_augment_prob: 'None' # 'None' # [0.04, 0.84, 0.11, 0.01]
use_maxlen: True # True, False
model_type: 'weak_cnn' # cnn, weak_cnn, lstm, transformer
cnn:
  dis_emb_dim: 256
  hidden_dim: 256
  num_layers: 4
  kernel: 3
  use_batchnorm: True
lstm:
  dis_emb_dim: 256
  hidden_dim: 256
  num_layers: 2
  bidirectional: True
transformer:
  dis_emb_dim: 256
  num_head: 8
  hidden_dim: 256
  num_layers: 4
weak_cnn:
  dis_emb_dim: 256
  hidden_dim1: 256
  hidden_dim2: 256
  use_second_conv: True

# Data loader
phn_max_length: 150
feat_max_length: 1300
concat_window: 11
sample_var: 0.15
repeat: 6 # repeat every sample x times

# Train
batch_size: 25
epoch: 2000 # for supervised training
step: 20000 # for unsupervised training
print_step: 100
eval_step: 200
gen_iter: 1
dis_iter: 3
gen_lr: 0.001
dis_lr: 0.002
sup_lr: 0.001
optimizer: 'radam' # radam

# gumbel
gan_gumbel: 'soft' # no, soft, hard
intra_gumbel: 'no'  # no, soft, hard
output_gumbel: 'no'  # no, soft, hard
