#Source path
train_feat_path: 'timit_for_GAN/audio/timit-train-mfcc-nor.pkl'
train_orc_bnd_path: 'timit_for_GAN/audio/timit-train-orc1-bnd.pkl'
train_phn_path: 'timit_for_GAN/audio/timit-train-phn.pkl'

dev_feat_path: 'timit_for_GAN/audio/timit-test-mfcc-nor.pkl'
dev_orc_bnd_path: 'timit_for_GAN/audio/timit-test-orc1-bnd.pkl'
dev_phn_path: 'timit_for_GAN/audio/timit-test-phn.pkl'

test_feat_path: 'timit_for_GAN/audio/timit-test-mfcc-nor.pkl'
test_orc_bnd_path: 'timit_for_GAN/audio/timit-test-orc1-bnd.pkl'
test_phn_path: 'timit_for_GAN/audio/timit-test-phn.pkl'

# Model
# regularizer
# ratio +: minimize, -:maximize
g_seg_ratio: 50 # for unsupervised segmentation: intra loss in origin paper # for no-boundary: the f1-loss between estimated number_of_phoneme/frame_num to frame_phone_ratio
g_same_ratio: 50 # makes the neighbor dist same
# g_maxprob_ratio # makes the highest prob inside frame-wise dist higher
g_entropy_ratio: 0 # make the frame-wise dist entropy low
# g_avg_maxprob_ratio
g_avg_entropy_ratio: -50 # makes the avg dist entropy high
# g_neighbor_avg_maxprob_ratio
g_neighbor_avg_entropy_ratio: 0 
d_gp_ratio: 1.0e-5 # gradient penalty
# generator
gen_hidden_size: 512
# others
frame_phone_ratio: 2 # estimated ratio of number_of_phoneme/frame_num
frame_temp: 0.9  # temp used for the output of the generator gumbel softmax
frame_balance_ratio: 0.2 # the max of the frame_balance
frame_balance_scheduler: [1, 1] # the step ratio of the start and end of the frame_balance # 0 to start, linear from start to end, 1 from end to final

# discriminator
target_augment_prob: 'None' # 'None' # [0.04, 0.84, 0.11, 0.01]
use_maxlen: True # True, False
model_type: 'weak_cnn' # cnn, weak_cnn, lstm, transformer
cnn:
  dis_emb_dim: 256
  hidden_dim: 256
  num_layers: 4
  kernel: 3
  use_batchnorm: True
lstm:
  dis_emb_dim: 256
  hidden_dim: 256
  num_layers: 2
  bidirectional: True
transformer:
  dis_emb_dim: 256
  num_head: 8
  hidden_dim: 256
  num_layers: 4
weak_cnn:
  dis_emb_dim: 256
  hidden_dim1: 256
  hidden_dim2: 256
  use_second_conv: True
  window_per_phn: 3
  # gb: gumbel # used after the interpolation in the gradient penalty
  gb_tau: 1
  gb_hard: False
  # gp: gradient penalty
  gp_align_level: frame # can only set to 'frame'
  gp_inter_target: gumbel_resample
  gp_grad_target: gumbel_resample # 'prob', 'gumbel_resample'
  locations_grad: True
  neighbors_grad: True
local_cnn:
  dis_emb_dim: 256
  hidden_dim1: 256
  hidden_dim2: 256
  use_second_conv: True
  window_per_phn: 3
  gb_tau: 0.5
  gb_hard: True

# Data loader
phn_max_length: 75
feat_max_length: 777
concat_window: 11
sample_var: 0.15
repeat: 6 # repeat every sample x times
sample_range: [2,5]

# Train
batch_size: 20
epoch: 2000 # for supervised training
step: 20000 # for unsupervised training
print_step: 20
eval_step: 200
gen_iter: 1
dis_iter: 1
gen_lr: 0.001
dis_lr: 0.002
sup_lr: 0.001
optimizer: 'radam' # radam

# gumbel
gan_gumbel: 'soft' # no, soft, hard
intra_gumbel: 'no'  # no, soft, hard
output_gumbel: 'no'  # no, soft, hard
